on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  github-action-go:
    runs-on: ubuntu-latest
    steps:
      - name: Read secret
        id: get
        uses: andrii-zakurenyi/secret-vault-github-action-plugin@v0.10.0
        with:
          server: ${{ secrets.DSV_SERVER }}
          clientId: ${{ secrets.DSV_CLIENT_ID }}
          clientSecret: ${{ secrets.DSV_CLIENT_SECRET }}
          setEnv: true
          retrieve: |
            ${{ secrets.DSV_SECRET_PATH }} ${{ secrets.DSV_SECRET_DATA_KEY }} AS myVal1
            ${{ secrets.DSV_SECRET_PATH }} ${{ secrets.DSV_SECRET_DATA_KEY }} AS myVal2

      - name: Print secret
        run: echo ${{ steps.get.outputs.myVal1 }}

      - name: Print secret from env
        run: echo ${{ env.myVal2 }}
