on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  github-action-go:
    runs-on: ubuntu-latest
    steps:
      - name: Read secret
        id: get
        uses: andrii-zakurenyi/secret-vault-github-action-plugin@v0.8.0
        with:
          server: ${{ secrets.DSV_SERVER }}
          clientId: ${{ secrets.DSV_CLIENT_ID }}
          clientSecret: ${{ secrets.DSV_CLIENT_SECRET }}
          secretPath: ${{ secrets.DSV_SECRET_PATH }}
          secretDataKey: ${{ secrets.DSV_SECRET_DATA_KEY }}

      - name: Print secret
        run: echo ${{ steps.get.outputs.secretVal }}

      - name: Print secret from env
        run: echo ${{ env.secretEnvVal }}
