on:
  workflow_dispatch:

jobs:
  github-action-go:
    runs-on: ubuntu-latest
    steps:
      - name: Read secret
        id: get
        uses: mariiatuzovska/secret-vault-github-action-plugin@v2.1
        with:
          server: ${{ secrets.DSV_SERVER }}
          clientId: ${{ secrets.DSV_CLIENT_ID }}
          clientSecret: ${{ secrets.DSV_CLIENT_SECRET }}
          secretPath: ${{ secrets.DSV_SECRET_PATH }}
          secretDataKey: ${{ secrets.DSV_SECRET_DATA_KEY }}
      - name: Write secret
        run: echo ${{ steps.get.outputs.secretVal }}
